=== ameax/ameax-json-schema/schemas/ameax_sale.v1-0.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["meta", "identifiers", "customer", "subject", "sale_status", "selling_status", "user_external_id", "date", "amount", "probability"],
    "properties": {
      "meta": {
        "type": "object",
        "required": ["document_type", "schema_version"],
        "properties": {
          "document_type": {
            "type": "string",
            "enum": ["ameax_sale"]
          },
          "schema_version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+$"
          }
        }
      },
      "identifiers": {
        "type": "object",
        "required": ["external_id"],
        "properties": {
          "external_id": {
            "type": "string"
          },
          "ameax_internal_id": {
            "type": ["integer", "null"]
          }
        }
      },
      "customer": {
        "type": "object",
        "oneOf": [
          {
            "required": ["customer_number"]
          },
          {
            "required": ["external_id"]
          }
        ],
        "properties": {
          "customer_number": {
            "type": "string"
          },
          "external_id": {
            "type": "string"
          }
        }
      },
      "subject": {
        "type": "string"
      },
      "description": {
        "type": ["string", "null"]
      },
      "sale_status": {
        "type": "string",
        "enum": ["active", "inactive", "completed", "cancelled","terminated","lost","won"]
      },
      "selling_status": {
        "type": "string",
        "enum": ["identification", "acquisition", "qualification", "proposal", "sale"]
      },
      "user_external_id": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "amount": {
        "type": "number",
        "minimum": 0,
        "multipleOf": 0.01,
        "pattern": "^\\d+\\.\\d{2}$"
      },
      "probability": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
      },
      "close_date": {
        "type": "string",
        "format": "date",
        "pattern": "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
      },
      "rating": {
        "type": "object",
        "required": ["relationship", "proposition", "trust", "competition", "need_for_action", "buying_process", "price"],
        "properties": {
          "relationship": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "proposition": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "trust": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "competition": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "need_for_action": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "buying_process": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          },
          "price": {
            "type": "object",
            "required": ["rating", "source"],
            "properties": {
              "rating": {
                "type": "integer",
                "minimum": 1,
                "maximum": 7
              },
              "source": {
                "type": "string",
                "enum": ["known", "assumed", "guessed"]
              }
            }
          }
        }
      },
      "custom_data": {
        "type": ["object", "null"],
        "additionalProperties": true
      }
    }
  }

=== ameax/ameax-json-schema/examples/ameax_sale.json
{
    "meta": {
      "document_type": "ameax_sale",
      "schema_version": "1.0"
    },
    "identifiers": {
      "external_id": "S234"
    },
    "customer": {
      "customer_number": "12345",
      "external_id": "X234"
    },
    "subject": "Opportunity 12345",
    "description": "Description of the opportunity",
    "sale_status": "active",
    "selling_status": "identification",
    "user_external_id": "JD",
    "date": "2025-02-01",
    "amount": 1000.00,
    "probability": 50,
    "close_date": "2025-07-01",
    "rating": {
      "relationship": {
        "rating": 4,
        "source": "known"
      },
      "proposition": {
        "rating": 3,
        "source": "assumed"
      },
      "trust": {
        "rating": 5,
        "source": "known"
      },
      "competition": {
        "rating": 2,
        "source": "guessed"
      },
      "need_for_action": {
        "rating": 4,
        "source": "known"
      },
      "buying_process": {
        "rating": 3,
        "source": "assumed"
      },
      "price": {
        "rating": 4,
        "source": "known"
      }
    },
    "custom_data": {
      "xsa_category": "industry",
      "what_ever": "x12"
    }
  }
