=== ameax/ameax-json-schema/schemas/ameax_private_person_account.v1-0.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "meta": {
      "type": "object",
      "properties": {
        "document_type": { "type": "string", "enum": ["ameax_private_person_account"] },
        "schema_version": { "type": "string" },
        "import_status": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "required": ["document_type", "schema_version"]
    },
    "salutation": { "type": ["string", "null"], "enum": ["Mr.", "Ms.", "Mx.", null] },
    "honorifics": { "type": ["string", "null"] },
    "firstname": { "type": "string" },
    "lastname": { "type": "string" },
    "date_of_birth": { "type": ["string", "null"], "format": "date" },
    "identifiers": {
      "type": "object",
      "properties": {
        "customer_number": { "type": ["string", "null"] },
        "external_id": { "type": ["string", "integer", "null"] },
        "ameax_internal_id": { "type": ["integer", "null"] }
      }
    },
    "address": {
      "type": "object",
      "properties": {
        "route": { "type": ["string", "null"] },
        "house_number": { "type": ["string", "null"] },
        "postal_code": { "type": "string" },
        "locality": { "type": "string" },
        "country": { "type": "string", "pattern": "^[A-Z]{2}$" }
      },
      "required": ["postal_code", "locality", "country"]
    },
    "communications": {
      "type": ["object", "null"],
      "properties": {
        "phone_number": { "type": ["string", "null"] },
        "mobile_phone": { "type": ["string", "null"] },
        "email": { "type": ["string", "null"], "format": "email" },
        "fax": { "type": ["string", "null"] }
      }
    },
    "agent": {
      "type": ["object"],
      "properties": {
        "external_id": { "type": ["string", "null"] }
      }
    },
    "custom_data": {
      "type": ["object", "null"],
      "additionalProperties": true
    }
  },
  "required": ["meta", "firstname", "lastname", "address"],
  "additionalProperties": false
}

=== ameax/ameax-json-schema/examples/ameax_private_person.json
{
  "meta": {
    "document_type": "ameax_private_person_account",
    "schema_version": "1.0",
    "import_mode": null
  },
  "salutation": "Mr.",
  "honorifics": "Dr.",
  "firstname": "John",
  "lastname": "Doe",
  "date_of_birth": "1980-05-12",
  "identifiers": {
    "customer_number": "123456",
    "ameax_internal_id": 987654
  },
  "address": {
    "route": "Musterstra√üe",
    "house_number": "12a",
    "postal_code": "12345",
    "locality": "Berlin",
    "country": "DE"
  },
  "communications": {
    "phone_number": "+49 30 987654",
    "mobile_phone": "+49 151 12345678",
    "email": "john.doe@example.com",
    "fax": "+49 30 765432"
  },
  "agent": {
    "external_id": "ms"
  },
  "custom_data": {
    "what_ever": "5"
  }
}
